In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.3'

In [4]:
## List of integers

L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
## check type of index 0

type(L[0])

int

In [7]:
## a list of strings

L2 = [str(c) for c in L]

In [8]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [9]:
type(L2[0])

str

In [10]:
## heterogeneous lists

L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

# Fixed-Type Arrays in Python

In [11]:
import array
L = list(range(10))
A = array.array('i', L) ## Here 'i' is a type code indicating the contents are integers.
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
T = list(range(30))
T

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [16]:
D = array.array("i", T)
D

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## Much more useful, however, is the ndarray object of the NumPy package.

In [17]:
## Creating Arrays from Python Lists

# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [18]:
## If types do not match, NumPy will upcast if possible (here, integers are upcast to floating point):

np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [19]:
## If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [20]:
## here’s one way of initializing a multidimensional array using a list of lists:

# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Create arrays from scratch

In [21]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# 5x7 fillled with integer of 2s

np.full((5,7), 2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [29]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [34]:
## array of 1

np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [35]:
np.ones(10) ## float

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.zeros(10) ## float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
np.zeros((3,4), dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
np.full((5, 9), 10)

array([[10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [41]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
## 0 to 50 in 5 increament

np.arange(0, 50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [44]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
## 10 values evenly space between 1 and 20

np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [46]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [47]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.04532735, 0.49638665, 0.22899336],
       [0.04677012, 0.08581702, 0.38906753],
       [0.66230592, 0.07063135, 0.50004107]])

In [48]:
## 4 x 4 betwen 0 and 1

np.random.random((4, 4))

array([[0.33065801, 0.33948921, 0.15572336, 0.54347371],
       [0.98843631, 0.59872099, 0.51470656, 0.73815586],
       [0.47014123, 0.68132479, 0.6538148 , 0.63378731],
       [0.90097931, 0.25096881, 0.42313034, 0.81915848]])

In [51]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.66335312,  0.90002368, -0.54154019],
       [ 0.68791305,  0.79670969, -0.24026859],
       [ 0.5415528 , -1.34033276,  1.19395445]])

In [52]:
## mean 4 sd 2

np.random.normal(4, 2, (3, 3))

array([[3.99438855, 3.98486007, 4.18328684],
       [0.5469345 , 4.06244798, 6.73063463],
       [6.28468572, 5.80272808, 4.6613168 ]])

In [53]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[6, 7, 1],
       [1, 3, 1],
       [0, 5, 8]])

In [54]:
## 4x 4 between 0 and 20

np.random.randint(0, 20, (4, 4))

array([[ 6, 15, 16, 14],
       [ 0,  8,  0, 16],
       [13,  6,  0,  9],
       [ 9, 11, 17, 15]])

In [55]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
## 4x4

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

# NumPy Standard Data Types